config/routes.rb
Rails.application.routes.draw do
 root "splash#index"
  devise_for :users
  resources :user
  resources :categories
  resources :transactions
  
   devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :transactions, dependent: :destroy
  has_one_attached :icon
  belongs_to :user

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :Categories, dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :transactions, foreign_key: :author_id
  has_many :categories

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(_resource)
    categories_path
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
    @transactions = Transaction.order(created_at: :desc)
  end

  def show; end

  def new
    @category = Category.new
    @category = current_user.categories.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user
    @category = current_user.categories.build(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transaction, only: %i[show edit update destroy]

  def index
    @category = Category.find_by(id: params[:category_id])
    if @category
      @transactions = @category.transactions.order(created_at: :desc)
      @total = @category.transactions.sum(:amount)
    else
      flash[:error] = 'Category not found'
      redirect_to categories_path
    end
  end

  def show; end

  def new
    @transaction = Transaction.new
  end

  def edit; end

  def create
    @transaction = Transaction.create(transaction_params)
    @transaction.author = current_user

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_url(@transaction), notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <%= link_to transactions_path(category_id: category.id), class: "card-link" do %>
    <div class="card">
    
      <div class="icon">
      <%= image_tag(category.icon) %>
      </div>

      <div class="text-center">
      <h6 class="text-muted"><%= category.name %></h6>
      </div>

      <div class="amount">
  <p>$ <%= number_with_precision(category.transactions.sum(:amount), precision: 2, delimiter: ',') %></p>
</div>
     
     

    </div>
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
<div class="container">
  

  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="sign-color">
    <div >
      <% form.label :name,%>
      <%= form.text_field :name, id: "Name", placeholder: "Name", class: "form-control p-3 mb-3" %>
    </div>

    <div class="form-control p-3 mb-3">
      <%= form.label :icon, id: "Icon", style: "display: block" %>
      <%= form.file_field :icon, class:"form-control", type:"file", id:"formFile"%>
    </div>
  </div>
</div>

<footer>
  <div class="actions" >
      <%= form.submit "Save", class: "save-btn"%>
    </div>
  </footer>
<% end %>

app/views/categories/edit.html.erb
<nav class="header">
    <%= image_tag(image_path("BIZZ-01.png"), alt: "logo", class: "logo") %>
  <div>
    <p> EDIT CATEGORY </p>
  </div>
  <div>
    <%= link_to "Back", categories_path, class: "back" %>
  </div>
</nav>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<main class="main-style">

<nav class="header">
    <%= image_tag(image_path("BIZZ-01.png"), alt: "logo", class: "logo") %>
  <div>
    <p> CATEGORIES </p>
  </div>
  <div>
    <%= link_to "Back", root_path, class: "back" %>
  </div>
</nav>

<div class="text-capitalize ">
    <h6> <%= link_to "sign out", destroy_user_session_path, method: :delete, class: "sign-out  initialism text-danger" %></h6>
    </div>

<div class="container">
  <div id="categories">
    <% if @categories.empty? %>
      <div class="message">There are no categories to display. Add one.</div>
    <% else %>
      <% @categories.each do |category| %>
        <%= render category %>
      <% end %>
    <% end %>
  </div>
  </div>


  <footer>
  <div class="actions">
  <%= link_to "New category", new_category_path, class: "new-cate" %>
  </div>
  </footer>
</main>

app/views/categories/new.html.erb
<nav class="header">
    <%= image_tag(image_path("BIZZ-01.png"), alt: "logo", class: "logo") %>
  <div>
    <p> NEW CATEGORY </p>
  </div>
  <div>
    <%= link_to "Back", categories_path, class: "back" %>
  </div>
</nav>

<div class="input-group">
  <%= link_to categories_path, class: "back-link" do %>
    <i class="bi bi-arrow-left"></i>
  <% end %>
    <i class="bi bi-list"></i>
</div>
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<nav class="header">

    <%= image_tag(image_path("BIZZ-01.png"), alt: "logo", class: "logo") %>
  <div>
    <p> ADDED CATEGORY </p>
  </div>
  <div>
    <%= link_to "Back", categories_path, class: "back" %>
  </div>

</nav>

<div class="container">
<%= render @category %>

<div class="edit-delete">
<div>
  <%= link_to "Edit category", edit_category_path(@category) %>
  </div>
  <%= link_to "Delete category", @category, method: :delete %>
</div>

</div>


<footer>
<div class="actions">
 <%= link_to "Back to categories", categories_path %>
 </div>
 </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BizApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "registration", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "header", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav>
    
  </nav>
   
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
   
  </body>
</html>

app/views/partials/_header.html.erb
<nav class="header">
 
    <%= image_tag(image_path("BIZZ-01.png"), alt: "logo", class: "logo") %>

  <div>
    <p><%= page %></p>
  </div>
  <div>
    
  </div>
</nav>

app/views/splash/index.html.erb
<main>
<div class="splash container">
  <%= image_tag(image_path("BIZZ-01.png"), alt: "logo", class:"splash-logo") %>
  <p>Keep truck of all your transactions</p>
  <div>
  <div class="d-grid gap-2">
    <%= link_to "LOG IN", new_user_session_path, class: "btn btn-primary-custom" %>
    <%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-primary-custom" %>
</div>
</main>
</div>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>

  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="sign-color container">
    <div class="field form-div">
      <% form.label :name, id: "Name", style: "display: block" %>
      <%= form.text_field :name, placeholder: "Name", class: "form-input" %>
    </div>

    <div class="field form-div">
      <%= form.label :amount, id: "Amount", style: "display: block" %>
      <%= form.text_field :amount, type: :number, class: "form-input" %>
    </div>

    <div class="field form-div">
      <%= form.select :category_id, options_for_select([['Select a category', '']] + Category.all.map { |c| [c.name, c.id] }), {}, { class: "form-input" } %>
    </div>
  </div>



    <footer>
    <div class="actions">
      <%= form.submit "Save", class: "save-btn" %>
    </div>
  </footer>
  

<% end %>

app/views/transactions/_transaction.html.erb
<div class="card w-100 shadow-sm bg-white mb-2  d-flex justify-content-between">
<div class= "row g-0">
  <div class="col p-2">
    <%= transaction.name %>
  </div>
  <div class="col p-2">
    <p>
      $ <%= transaction.amount %>
    </p>
  </div>
  </div>
</div>

app/views/transactions/edit.html.erb
  
  <nav class="header">

    <%= image_tag(image_path("BIZZ-01.png"), alt: "logo", class: "logo") %>
  <div>
    <p> EDIT TRANSACTION </p>
  </div>
  <div>
    <%= link_to "Back", new_transaction_path, class: "back" %>
  </div>

</nav>
  
  


<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<nav class="header">
    <%= image_tag(image_path("BIZZ-01.png"), alt: "logo", class: "logo") %>
  <div>
    <p> TRANSACTIONS </p>
  </div>
  <div>
    <%= link_to "Back", categories_path, class: "back" %>
  </div>
</nav>

<p style="color: green"><%= notice %></p>

<div class="container">
<div id="transactions">
  <% if @transactions.empty? %>
    <div class="message">There are no transactions to display. Add one.</div>
  <% else %>
    <% @transactions.each do |transaction| %>
      <%= render transaction %>
    <% end %>
  <% end %>
</div>

<div class="total bg-info text-white">
  <h5>Total Amount:</h5>
  <p>$<%= @total %></p>
</div>

<div class="mb-4">
  <%= link_to "New transaction", new_transaction_path, class: "btn btn-secondary" %>
</div>

<div>
  <%= link_to "Show this transaction", @transaction %>
</div>
</div>

<footer>
<div class="actions">
 <%= link_to "Back to transactions", transactions_path %>
 </div>
 </footer>

app/views/transactions/new.html.erb
<nav class="header">

    <%= image_tag(image_path("BIZZ-01.png"), alt: "logo", class: "logo") %>
  <div>
    <p> NEW TRANSACTION </p>
  </div>
  <div>
    <%= link_to "Back", new_transaction_path, class: "back" %>
  </div>

</nav>


<div class="new-head">
  <%= link_to transactions_path(category_id: 1), class: "back-link" do %>
    <i class="bi bi-arrow-left"></i>
  <% end %>
</div>

<%= render "form", transaction: @transaction %>

app/views/transactions/show.html.erb
<nav class="header">

    <%= image_tag(image_path("BIZZ-01.png"), alt: "logo", class: "logo") %>
  <div>
    <p> SHOW</p>
  </div>
  <div>
    <%= link_to "Back", new_category_path, class: "back" %>
  </div>

</nav>



<p style="color: green"><%= notice %></p>

<div class="container">
<%= render @transaction %>
</div>

<div class="edit-delete">
<div> 
  <%= link_to "Edit transaction", edit_transaction_path(@transaction) %>
  </div>

  <%= link_to "Delete transaction", @transaction, method: :delete %>
</div>

<footer>
<div class="actions">
<%= link_to "Back to transactions", transactions_path %>
</div>
</footer>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>
  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>